# Biblical RAG LLM MVP 1

This notebook tests mistral:instruct's ability to read a Bible that is recursively chunked.

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import json
import os
from uuid import uuid4

# Open King James Bible.
data_dir = os.path.join(os.path.dirname(os.getcwd()), 'data')
kjv_df = pd.read_csv(os.path.join(data_dir, 'en_kjv.csv'), index_col='index')
kjv_df.head()

,language,translation,book,chapter,verse,text
index,,,,,,
0,en,kjv,Gen,1,1,In the beginning God created the heaven and th...
1,en,kjv,Gen,1,2,"And the earth was without form, and void; and ..."
2,en,kjv,Gen,1,3,"And God said, Let there be light: and there wa..."
3,en,kjv,Gen,1,4,"And God saw the light, that it was good: and G..."
4,en,kjv,Gen,1,5,"And God called the light Day, and the darkness..."

In [2]:
# Open metadata table.
book_metadata = pd.read_csv(os.path.join(data_dir, 'metadata', 'books.csv'))
book_metadata.loc[book_metadata['book'].isin(['Numbers', 'Jonah', 'Ruth', 'Mark', 'Titus', 'Revelation'])]

,book,chapters,verses,avg verse per chapter,testament,category,author,abbreviation
3,Numbers,36,1288,36,old,law,Moses,Num
7,Ruth,4,85,21,old,writing,Samuel,Ruth
31,Jonah,4,48,12,old,prophet,Jonah,Jonah
40,Mark,16,678,42,new,gospel,Mark,Mark
55,Titus,3,46,15,new,epistle,Paul,Titus
65,Revelation,22,404,18,new,revelation,John,Rev

In [6]:
psalm_metadata = pd.read_csv(os.path.join(data_dir, 'metadata', 'psalms.csv'))
psalm_metadata.loc[psalm_metadata['psalm'].isin([1, 5, 42, 50, 89, 90, 127])]

     psalm         author
0        1      Anonymous
4        5          David
41      42  Sons of Korah
49      50          Asaph
88      89          Ethan
89      90          Moses
126    127        Solomon

## Prepare the Data

In [3]:
# Combine all verses into book chapters.
kjv_books = {}
book_title_list = book_metadata['abbreviation'].values
tween = ' ' # What goes between each verse
verse_total = book_metadata['verses'].sum() # Index of the final verse
print("Begin forming books...")
for book in book_title_list:
	full_title = book_metadata.loc[book_metadata['abbreviation'] == book]['book'].values[0]
	number_of_chapters = book_metadata.loc[book_metadata['abbreviation'] == book]['chapters'].values[0]
	for chapter in range(number_of_chapters):
		chapter_df = kjv_df.loc[(kjv_df['book'] == book) & (kjv_df['chapter'] == chapter+1)]
		full_title = book_metadata.loc[book_metadata['abbreviation'] == book]['book'].values[0]
		full_chapter_text = ''
		for index, row in chapter_df.iterrows():
			if row['chapter'] == chapter+1:
		   		full_chapter_text += row['text'] + tween
		kjv_books[full_title + ' | ' + str(chapter+1)] = full_chapter_text.rstrip() # Separate with a pipe for easy splitting later
print("Finished forming books!")
# Store in file
out_path = os.path.join(data_dir, 'en_kjv.json')
if not os.path.isfile(out_path):
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(kjv_books, f, indent=4, ensure_ascii=False)

Begin forming books...
Finished forming books!

In [4]:
# This method provides the chapter and verse citation for metadata.
def get_citation(text, df):
	citation = {} # Key is chapter number; value is list of verse numbers
	for index, row in df.iterrows():
		if row['text'] in text.page_content:
			if row['chapter'] in citation.keys():
				citation[row['chapter']].append(row['verse'])
			else:
				citation[row['chapter']] = [row['verse']]
	mykeys = []
	for key in citation.keys():
		mykeys.append(key)
	if len(mykeys) == 1:
		result = str(mykeys[0]) + ':' + str(citation[mykeys[0]][0]) + '-' + str(citation[mykeys[0]][-1])
	elif len(mykeys) >= 1:
		result = str(mykeys[0]) + ':' + str(citation[mykeys[0]][0]) + '-' + str(mykeys[-1]) + ':' + str(citation[mykeys[-1]][-1])
	else:
		result = ''
	return result

In [7]:
from langchain_core.documents import Document
from langchain_core.runnables import RunnablePassthrough

local_llm = 'llama3'
dimensions=300

# Convert each book into a document.
def document_verses(doc_dict):
    documents = []
    for doc_index, doc in enumerate(doc_dict):
        title = doc.split(' | ')[0] # Some titles have a space (e.g. 1 Samuel), so the pipe is needed!
        if title == 'Psalms':
            author = psalm_metadata.loc[psalm_metadata['psalm'] == int(doc.split(' | ')[1])]['author'].values[0]
        else:
            author = book_metadata.loc[book_metadata['book'] == title]['author'].values[0]
        doc = Document(
            page_content=doc_dict[doc],
            metadata={
                'title': title,
                'citation': doc.replace(' | ', ' '),
                'author': author,
                'book_index': doc_index
            },
            id=str(uuid4())
        )
        documents.append(doc)
    return documents

# Split the documents.
split_docs = document_verses(kjv_books)
print("Documents split. There are {}.".format(len(split_docs)))

Documents split. There are 1189.

In [8]:
# Check the documents that have been split
'''print("There are {} chunks.\n".format(len(split_docs)))
for i in range(8):
    r = split_docs[i*100]
    print("{} ({}; by {})".format(r.page_content, r.metadata['citation'], r.metadata['author']))###### TO DO: CHAPTER AND VERRSE REFS ####
    print('')'''

'print("There are {} chunks.\n".format(len(split_docs)))\nfor i in range(8):\n    r = split_docs[i*100]\n    print("{} ({}; by {})".format(r.page_content, r.metadata[\'citation\'], r.metadata[\'author\']))###### TO DO: CHAPTER AND VERRSE REFS ####\n    print(\'\')'

## Store the Data

In [9]:
from langchain_ollama import OllamaEmbeddings, OllamaLLM
from langchain_community.vectorstores import FAISS

print("Begin instantiating LLM.")
llm = OllamaLLM(model='mistral:instruct')
print("LLM instantiated.")
embedding = OllamaEmbeddings(model='mistral:instruct')
vectorstore = FAISS.from_documents(split_docs, embedding)
print("Vector store instantiated.")

Begin instantiating LLM.
LLM instantiated.
Vector store instantiated.

### Save & Load

In [ ]:
vector_file = os.path.join(data_dir, 'bible_vectostore_chapters')
vectorstore.save_local(vector_file)
print("File saved.")

In [ ]:
from langchain_ollama import OllamaEmbeddings
from langchain_community.vectorstores import FAISS

embedding = OllamaEmbeddings(model='mistral:instruct')
vector_file = os.path.join(data_dir, 'bible_vectostore_chapters')
vectorstore = FAISS.load_local(vector_file, embedding, allow_dangerous_deserialization=True)#.as_retriever() if you want to load it as a retriever
print("File loaded.")

# RAG Chain Tests
I will test several RAG chain settings below. There are 1189 Bible chapters in the RAG. First I will test gathering 1/10th & finally 1/100th of the chapters with MMR at 0.7, 0.5, and 0.3. Then I will choose the best one and try gathering fewer and fewer documents.

## Fetch 1/10th of the docs & give 1/100th of the docs with MMR search & lambda 0.7

In [10]:
from langchain.chains import RetrievalQA

print("Begin instantiating retriever.")
retriever = vectorstore.as_retriever(
    fetch_k=len(split_docs)//10,
    k=len(split_docs)//100,
    search_type='mmr',
    lambda_mult=0.7
)
print("Retriever instantiated.")
qa = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever
)
print("RAG chain instantiated.")

Begin instantiating retriever.
Retriever instantiated.
RAG chain instantiated.

## Test the RAG Model

In [11]:
questions = [
    "Where did Jesus talk about wine?",
    "Who was Abraham's son?",
    "Where did God send Jonah? And where did Jonah try to go instead?",
    "Who are Luke's books addressed to?",
    "Which psalm says that angels will protect you even from dashing your foot against a stone?",
    "Why did God regret making Saul the King of Israel?",
    "What did Paul disagree with Peter about according to Paul's letter to the Galatians? Who was right?",
    "Why did Peter feel comfortable eating pork and shellfish after receiving the Holy Spirit?",
    "When Jesus mentions that Moses lifted the serpent in the wilderness (John 3:14), what is He referencing?",
    "What is the genealogy of Enoch going back to Adam?",
    "Why did God flood the world in the time of Noah?",
    "What are the similarities between Daniel's prophesies and Revelation's prophesies?"
]
print("There are {} questions in the test suite.".format(len(questions)))

for question in questions:
    answer = qa.invoke(question)
    print(answer['query']+'\n'+answer['result']+'\n')

There are 12 questions in the test suite.
Where did Jesus talk about wine?
 In the New Testament, there are several instances where Jesus refers to or uses wine in His teachings. Here are a few examples:

1. At the Wedding at Cana (John 2:1-11) - This is one of the earliest accounts of Jesus's ministry and His first miracle. At a wedding, the hosts ran out of wine. Jesus told His disciples to fill six large jars with water, which they did. He then turned the water into wine, making it the best wine of the occasion.

2. The Parable of the Lost Sheep (Matthew 18:12-14) - In this parable, Jesus uses wine as a metaphor to illustrate God's joy in finding a lost soul and bringing them back to the fold. He says that there is more rejoicing in heaven over one sinner who repents than over ninety-nine righteous persons who do not need to repent.

3. The Last Supper (Matthew 26:26-29, Mark 14:22-25, Luke 22:17-20) - During the Last Supper with His disciples, Jesus instituted the Lord's Supper or Eucharist. He took a cup of wine and said that it represented His blood, which would be shed for the forgiveness of sins.

4. The Parable of the Wicked Vineyard Workers (Matthew 20:1-16) - In this parable, Jesus uses wine to illustrate the Kingdom of God and how God's grace is freely given to all who come to Him.

These passages are just a few examples where Jesus talks about or refers to wine in the New Testament.

Who was Abraham's son?
 The answer to your question is not explicitly mentioned in the text you provided, as it does not discuss Abraham's sons directly. However, from other parts of the Bible, we know that Abraham had two main sons by his concubine Hagar: Ishmael, and Isaac, who was born later to Sarah.

Where did God send Jonah? And where did Jonah try to go instead?
 In the scripture you provided, there is no mention of Jonah. The story of Jonah is a separate account in the Old Testament. According to that story, God commanded Jonah to go to the city of Nineveh and warn its people to repent because their wickedness had reached a great height. However, Jonah tried to flee from this command by boarding a ship heading in the opposite direction, toward Tarshish. When a violent storm arose and threatened the ship, the sailors learned that Jonah was on board and they asked him about the cause of the storm. Jonah admitted that he had disobeyed God and the sailors threw him overboard to calm the sea. A great fish then swallowed Jonah, but afterward, God commanded the fish to spit Jonah out onto dry land, whereupon Jonah obeyed God's command and went to Nineveh to preach repentance.

Who are Luke's books addressed to?
 The books attributed to Luke in the New Testament (the Gospel According to Luke and Acts of the Apostles) are not directly addressed to any specific person. However, it is traditionally believed that they were written for a wide audience of early Christians.

Which psalm says that angels will protect you even from dashing your foot against a stone?
 The Psalm that mentions angels protecting one from stumbling or dashing one's foot against a stone is Psalm 91. Specifically, verse 12 states, "The LORD says, 'I will rescue those who love me. I will protect those who trust in my name. When they call on me, I will answer; I will be with them in trouble. I will rescue and honor them. With long life I will satisfy them and show them my salvation.'" While the context is not explicitly about angels protecting from stumbling, it does suggest that God's protection can extend to preventing such mishaps. In the story of Lot and his family, angels did protect him and his family by leading them out of Sodom before its destruction, but they could not prevent his wife from looking back and turning into a pillar of salt.

Why did God regret making Saul the King of Israel?
 The passage provided does not mention any instance where God regretted making Saul the king of Israel. In fact, in the Bible, it is recorded that God chose Saul to be the first king of Israel (1 Samuel 9:16), but later on, due to Saul's disobedience and rebellion against God's commands, he was rejected as king and replaced by David (1 Samuel 15-31). So, if you are referring to a specific event where God "regretted" making Saul king, the passage provided does not contain that information.

What did Paul disagree with Peter about according to Paul's letter to the Galatians? Who was right?
 In his letter to the Galatians, Paul disagreed with Peter (also known as Cephas) over the issue of circumcision and adherence to Jewish laws. This disagreement is often referred to as the "Jerusalem Council" or "Council of Jerusalem."

According to Acts 15:1-35, there were some Jews who came from Judea and taught that Gentile Christians should be circumcised and follow Jewish customs in order to be saved. Peter, James (also known as Jacob), John, and other leaders in the Jerusalem church met to discuss this matter. They decided that while it was not necessary for Gentiles to be circumcised or follow Jewish food laws, they should abstain from meat offered to idols, from sexual immorality, from eating strangled animals, and from blood.

However, Paul disagreed with Peter about the importance of adhering to these Jewish customs. In his letter to the Galatians (chapter 2), he wrote that he had seen Peter withdraw himself when some Jews came from Jerusalem and that Peter "was in no way guided by the truth of the gospel" (Galatians 2:14, NIV). Paul accused Peter of hypocrisy because he was eating with Gentiles but then withdrew when Jewish Christians arrived.

It is unclear if Peter and Paul ever resolved their disagreement, but the church eventually reached a consensus that adherence to Jewish customs was not necessary for salvation. According to Christian tradition, this consensus was solidified at the Council of Jerusalem.

In terms of who was "right," it's important to note that both Paul and Peter were key figures in the early Christian movement, and their differing perspectives on this issue reflect the diversity and complexity of early Christianity. From a historical perspective, the church eventually adopted a position closer to Paul's view that salvation is available to all, regardless of adherence to Jewish customs. However, it's important to remember that both Peter and Paul had unique insights into the gospel message, and their disagreements serve as an important reminder of the ongoing dialogue and debate within Christianity.

Why did Peter feel comfortable eating pork and shellfish after receiving the Holy Spirit?
 The passage provided does not mention Peter or the consumption of pork or shellfish in connection to receiving the Holy Spirit. In the New Testament, there is a passage in Acts 10 that describes Peter having a vision where he is told by God to eat animals considered unclean under the Mosaic law (including pigs and other animals), which he initially refuses to do but eventually does as part of his understanding that God shows no partiality and that all people, including non-Jews, are acceptable in His sight. This event is often used to explain why some early Christians felt comfortable eating these foods after receiving the Holy Spirit. However, this passage does not directly address Peter's feelings or beliefs about eating pork and shellfish specifically after receiving the Holy Spirit.

When Jesus mentions that Moses lifted the serpent in the wilderness (John 3:14), what is He referencing?
 In John 3:14, when Jesus mentions Moses lifting the serpent in the wilderness, He is referring to an event described in Numbers 21:4-9. The Israelites were traveling through the wilderness, and due to their disobedience, God sent venomous snakes among them, resulting in many bites and deaths. The people repented of their sin and asked Moses to intercede for them with God. God instructed Moses to make a bronze snake and place it on a pole, and anyone who had been bitten by a snake could look at the bronze snake (also called a "fiery serpent") and live. This event is significant because it serves as an Old Testament type or foreshadowing of Jesus Christ, who was lifted up (crucified) on the cross for our sins, so that anyone who believes in Him may have eternal life.

What is the genealogy of Enoch going back to Adam?
 The genealogy of Enoch going back to Adam can be found in the Book of Genesis, specifically in Chapter 5. Here it is:

1. Adam (the first man)
2. Seth (son of Adam)
3. Enosh (son of Seth)
4. Kenan (son of Enosh)
5. Mahalalel (son of Kenan)
6. Jered (son of Mahalalel)
7. Enoch (son of Jered)
8. Methuselah (son of Enoch)
9. Lamech (son of Methuselah)
10. Noah (son of Lamech)

Enoch is the seventh in this lineage, and he is noteworthy because it is said that he "walked with God; and he was not, for God took him" (Genesis 5:24). This means Enoch did not die but was taken directly to heaven.

Why did God flood the world in the time of Noah?
 God flooded the world during the time of Noah as a result of the widespread corruption and wickedness that had overtaken humanity. The Bible explains this in Genesis 6:5, which states, "The LORD saw that the wickedness of humankind was great in the earth, and that every inclination of the thoughts of their hearts was only evil continually." God decided to destroy all life on Earth, except for Noah, his family, and the animals they took with them on the Ark. This act was intended as a means of cleansing the world of sin and starting over, in accordance with God's desire for righteousness and justice.

What are the similarities between Daniel's prophesies and Revelation's prophesies?
 The books of Daniel and Revelation in the Bible both contain apocalyptic visions, which describe end-times events and the ultimate triumph of God. Here are some similarities between their prophesies:

1. Visions and Dreams: Both Daniel and John (the author of Revelation) receive visions and dreams from God, which serve as divine revelations about the future. These visions often include symbolic imagery that requires interpretation to understand their meanings.

2. Symbolic Imagery: The symbols used in both books are similar, such as four beasts representing kingdoms or empires, a woman giving birth to a child, a lamb or a man figure representing Jesus Christ, and seven-headed creatures or seven-sealed scrolls.

3. Sequence of Empires/Kingdoms: Both texts depict a sequence of world powers that rise and fall according to God's plan. In Daniel, it is the Babylonian, Medo-Persian, Greek, and Roman empires, while in Revelation, it is not explicitly stated but can be interpreted as a series of seven successive world systems.

4. Judgment and Punishment: Both books describe God's judgment upon wickedness and sin, including the destruction of evil kingdoms or empires, and the ultimate punishment of Satan and his followers.

5. New Heaven and New Earth: Both texts contain prophesies about a future time when God will establish a new heaven and a new earth, free from suffering, pain, and evil, in which righteousness dwells forever.

6. The Return of Christ: Both books describe the Second Coming of Jesus Christ to establish His kingdom on Earth and usher in the final judgment and the establishment of the New Heaven and New Earth.

7. The Ultimate Triumph of God: Both texts emphasize that, despite the appearance of chaos and defeat during times of evil dominion, God remains sovereign over all things, and His ultimate plan will prevail, culminating in the eternal victory of good over evil.

## Assessment: RAG -> 10th -> 100th w/ MMR @ 0.7 lambda
### Where did Jesus talk about wine?
In 2 of the examples, Jesus doesn't talk about wine (the parable of the lost sheep, and the parable of the vinyard workers). It's missing times when Jesus said that he was called a drunkard and when he said that you don't put new wine in an old wineskin because the wineskin will burst.
### Who was Abraham's son?
The model gets the answer right, but mentions that the RAG docs did not mention Abraham and his sons.
### Where did God send Jonah? And where did Jonah try to go instead?
The model gets the answer right, but mentions that the RAG docs did not mention Jonah's journeys.
### Who are Luke's books addressed to?
The model fails to mention Theophilus. It says that the books were written for many people, which is a common theory.
### Which psalm says that angels will protect you even from dashing your foot against a stone?
The model correctly identifies Psalm 91, verse 12, but misquites the verse and says that the verse does not explicitly mention angels and tripping on stones. **This is a strange hallucination.**
### Why did God regret making Saul the King of Israel?
The model correctly identifies that Saul was rejected for disobedience, but does not mention the specific act of disobedience (choosing not to kill the enemy king and cattle). The RAG text did not mention Saul.
### What did Paul disagree with Peter about according to Paul's letter to the Galatians? Who was right?
The model correctly identifies circumcision of gentiles and following Jewish law as the issue of disagreement. It does not want to say who is "right", but acknowledges that the early church agreed with Paul.
### Why did Peter feel comfortable eating pork and shellfish after receiving the Holy Spirit?
The model correctly identifies the vision Peter had, but says that the RAG model did not help.
### When Jesus mentions that Moses lifted the serpent in the wilderness (John 3:14), what is He referencing?
The model correctly identifies the reference to Numbers 21 and the bronze serpent statue.
### What is the genealogy of Enoch going back to Adam?
The model extracted the genealogy going to Noah (grandson of Enoch), which is more information than required. **This feels the most like a RAG extraction.**
### Why did God flood the world in the time of Noah?
The model correctly identifies the purpose of the flood.
### What are the similarities between Daniel's prophesies and Revelation's prophesies?
The model correctly identifies similarities between the 2 books.
### Score:
7/12
### RAG Fails:
4/12

## Fetch 1/10th of the docs & give 1/100th of the docs with MMR search & lambda 0.5

In [12]:
from langchain.chains import RetrievalQA

print("Begin instantiating retriever.")
retriever = vectorstore.as_retriever(
    fetch_k=len(split_docs)//10,
    k=len(split_docs)//100,
    search_type='mmr',
    lambda_mult=0.5
)
print("Retriever instantiated.")
qa = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever
)
print("RAG chain instantiated.")

Begin instantiating retriever.
Retriever instantiated.
RAG chain instantiated.

## Test the RAG Model

In [13]:
questions = [
    "Where did Jesus talk about wine?",
    "Who was Abraham's son?",
    "Where did God send Jonah? And where did Jonah try to go instead?",
    "Who are Luke's books addressed to?",
    "Which psalm says that angels will protect you even from dashing your foot against a stone?",
    "Why did God regret making Saul the King of Israel?",
    "What did Paul disagree with Peter about according to Paul's letter to the Galatians? Who was right?",
    "Why did Peter feel comfortable eating pork and shellfish after receiving the Holy Spirit?",
    "When Jesus mentions that Moses lifted the serpent in the wilderness (John 3:14), what is He referencing?",
    "What is the genealogy of Enoch going back to Adam?",
    "Why did God flood the world in the time of Noah?",
    "What are the similarities between Daniel's prophesies and Revelation's prophesies?"
]
print("There are {} questions in the test suite.".format(len(questions)))

for question in questions:
    answer = qa.invoke(question)
    print(answer['query']+'\n'+answer['result']+'\n')

There are 12 questions in the test suite.
Where did Jesus talk about wine?
 The New Testament of the Bible contains several references to Jesus talking about or using wine. One notable instance is at the Last Supper, where Jesus shared wine with His disciples (Matthew 26:27-29, Mark 14:23-25, Luke 22:17-20). Another example is when Jesus turned water into wine during a wedding in Cana (John 2:1-11). Additionally, there are other instances where Jesus mentions or uses the symbolism of wine to represent different aspects of His ministry and message (Matthew 9:17, Luke 5:37-39, Matthew 26:29, Mark 14:25, John 15:5). However, it's important to note that Jesus did not talk about wine in the way people often discuss it today, as a recreational or intoxicating beverage. Instead, He used it symbolically to illustrate spiritual concepts and truths.

Who was Abraham's son?
 Abraham did not have any sons mentioned in the given passage. The story revolves around Lot, who was a nephew to Abraham by marriage (Sarah and Lot's mother were sisters), and his family.

Where did God send Jonah? And where did Jonah try to go instead?
 In the Bible story you provided, it does not mention Jonah. The story is about Abraham and Sarah. If you are asking about Jonah, in another story from the Bible, God sent Jonah to Nineveh to warn its people to repent of their wickedness, but Jonah tried to go instead to Tarshish, which was a city in modern-day Spain or Portugal, as he did not want to go to Nineveh.

Who are Luke's books addressed to?
 The books attributed to Luke in the New Testament (the Gospel according to Luke, and the Acts of the Apostles) are not addressed to any specific individual. However, it is believed that they were written for a general audience, intended to spread the message of Jesus Christ and the early Christian church.

Which psalm says that angels will protect you even from dashing your foot against a stone?
 The psalm that mentions angels protecting you from stumbling over a stone can be found in Psalm 91:11-12. It reads, "For he will command his angels concerning you to guard you in all your ways; they will lift you up in their hands, so that you will not strike your foot against a stone." This passage emphasizes the protection and care that angels provide for those who trust in God.

Why did God regret making Saul the King of Israel?
 The passage provided does not contain information about God regretting making Saul the king of Israel. The events in this text describe interactions between Abraham, Sarah, and three unidentified men (possibly angels), as well as Abraham's negotiations with God regarding the destruction of Sodom and Gomorrah. There is no mention or suggestion that God regretted choosing Saul as king in this passage. To find information about God regretting making Saul the King, you would need to reference other texts from the Bible, such as 1 Samuel chapters 8-31. In those passages, it is described how God initially appoints Saul as king but eventually rejects him due to his disobedience and unfaithfulness.

What did Paul disagree with Peter about according to Paul's letter to the Galatians? Who was right?
 According to Paul's letter to the Galatians (Galatians 2:11-14), there was a disagreement between Paul and Peter (also known as Cephas) about the issue of circumcision. Paul contended that salvation comes through faith in Christ alone, without the necessity of following Jewish laws such as circumcision. He believed this message should be delivered to both Jews and Gentiles equally. On the other hand, Peter seemed to be compromising by behaving according to Jewish customs when he was around Jewish believers, but not when he was with Gentile believers.

In the eyes of Paul, Peter was acting inconsistently with the gospel message. However, it's important to note that this disagreement didn't lead to a permanent break between them, as they continued to work together in spreading the gospel (Galatians 2:9). This incident serves as an example of the importance of maintaining the consistency and purity of the gospel message.

As for who was "right" in this situation, it is a matter of interpretation and theological perspective. Some interpret Paul's criticism of Peter as a corrective measure to ensure the gospel message was being upheld consistently across all cultures and groups, while others see it as a temporary misunderstanding that was resolved through open dialogue and mutual understanding. Ultimately, both Paul and Peter played crucial roles in spreading the gospel, and their disagreement didn't diminish the impact of their respective ministries.

Why did Peter feel comfortable eating pork and shellfish after receiving the Holy Spirit?
 The text provided does not contain any information about Peter feeling comfortable eating pork or shellfish after receiving the Holy Spirit, as the story of Peter's vision and encounter with unclean animals is found in Acts 10, whereas the dietary laws regarding clean and unclean animals are detailed in Leviticus 11. In the New Testament, there are no instances where Peter is explicitly recorded to have eaten pork or shellfish as a result of receiving the Holy Spirit. The question seems to be based on a conflation of texts and theological interpretations not directly supported by the Bible itself.

When Jesus mentions that Moses lifted the serpent in the wilderness (John 3:14), what is He referencing?
 In the Old Testament book of Numbers, chapter 21, there is a story about the Israelites complaining to Moses during their journey through the desert after escaping from Egypt. God punished the Israelites by sending venomous snakes among them, and many Israelites were bitten and died. Moses prayed to the Lord, who instructed him to make a bronze serpent and mount it on a pole, so that anyone who was bitten could look at it and be healed. This event is what Jesus is referencing in John 3:14 when He says, "And as Moses lifted up the serpent in the wilderness, so must the Son of Man be lifted up." In this way, Jesus is using a metaphor to illustrate His role as the Savior who would be lifted up on the cross for the salvation of all people.

What is the genealogy of Enoch going back to Adam?
 The genealogy of Enoch going back to Adam can be found in the Book of Genesis (5:1-32). Here's a summary:

1. Enoch was the son of Cainan, who was the son of Enosh, who was the son of Seth, who was the third son of Adam and Eve.

2. Seth lived 912 years and had other sons and daughters. One of his sons was Enosh.

3. Enosh lived 905 years, fathering Kenan.

4. Kenan lived 910 years, fathering Mahalalel.

5. Mahalalel lived 895 years, fathering Jared.

6. Jared lived 962 years, fathering Enoch.

7. Enoch, also known as Metatron in later Jewish tradition, did not have children of his own. According to the biblical account, Enoch "walked with God" and was taken directly into heaven before his death (Genesis 5:24).

So, going back from Enoch:
- Enoch was the son of Jared
- Jared was the son of Mahalalel
- Mahalalel was the son of Kenan
- Kenan was the son of Enosh
- Enosh was the son of Seth
- Seth was the third son of Adam and Eve.

Why did God flood the world in the time of Noah?
 God flooded the world in the time of Noah as a result of rampant sin and wickedness among humanity, to the point where it grieved Him. He decided to destroy all life on Earth except for Noah, his family, and the animals they took into the ark. This event is described in the biblical book of Genesis (chapters 6-9).

What are the similarities between Daniel's prophesies and Revelation's prophesies?
 The books of Daniel and Revelation in the Bible contain apocalyptic or end-times prophecies. Here are some similarities between their prophesies:

1. Symbolic language: Both Daniel and Revelation use symbolic language, including visions, dreams, and beasts, to convey their messages. This can make interpretation challenging but also adds layers of meaning that may not be immediately apparent.

2. Judgment on the wicked: Both prophetic books contain descriptions of God's judgment on those who have transgressed against Him. This often includes punishments such as wars, plagues, and destruction.

3. Hope for the righteous: Despite the harsh judgments on the wicked, both books offer hope to the righteous, promising deliverance, salvation, and a new heaven and a new earth.

4. The coming of a Messiah or savior: Both Daniel and Revelation refer to a future figure who will bring about God's judgment, establish His kingdom, and save His people. In Daniel, this is often referred to as the "Son of Man," while in Revelation, it is frequently described as the "Lamb" or "Christ."

5. The role of Satan: Both books portray Satan as a powerful adversary of God, working against His people and seeking to deceive and mislead them.

6. A future judgment day: Both Daniel and Revelation describe a final day of judgment when all will be made right according to God's justice, and His enemies will be defeated and cast into eternal punishment.

7. The restoration of Israel: Both books contain prophecies regarding the restoration of Israel and the gathering of God's people from the four corners of the earth.

## Assessment RAG -> 10th -> 100th w/ MMR @ 0.5 lambda
### Where did Jesus talk about wine?
The model correctly identifies verses where Jesus talked about wine.
### Who was Abraham's son?
The model failed to answer the question, because the RAG model provided scriptures about Lot (Abraham's nephew).
### Where did God send Jonah? And where did Jonah try to go instead?
THe model correctly identidies Nineveh and Tarshish, but first says that the RAG texts are about Abraham and Sarah (more suitable to the previous question).
### Who are Luke's books addressed to?
The model fails to mention Theophilus. It says that the books were written for many people, which is a common theory.
### Which psalm says that angels will protect you even from dashing your foot against a stone?
The model correctly identifies Psalm 91, verse 12, and correctly quotes it.
### Why did God regret making Saul the King of Israel?
The model correctly identifies the reason for Saul's rejection, but the RAG texts are again about Abraham and Sarah. **Could the retrieval object be biased toward earlier texts?**
### What did Paul disagree with Peter about according to Paul's letter to the Galatians? Who was right?
The model correctly identifies the point of disagreement and where it is mentioned. The model does not want to say who is right, but mentions 2 common interpretations.
### Why did Peter feel comfortable eating pork and shellfish after receiving the Holy Spirit?
The model correctly identified the vision Peter had, but says the RAG texts did not mention it. The model is also in denial about Peter's feeling of liberty to eat pork and shellfish.
### When Jesus mentions that Moses lifted the serpent in the wilderness (John 3:14), what is He referencing?
The model correctly identified Numbers 21 and interpreted it as a symbol for Jesus' crucifixion.
### What is the genealogy of Enoch going back to Adam?
The model gets the answer right, but is redundant and formats the answer in a bad way.
### Why did God flood the world in the time of Noah?
The model correctly identidies the purpose of the flood.
### What are the similarities between Daniel's prophesies and Revelation's prophesies?
The model found clear similarities between the 2 books.
### Score:
10/12
### RAG Fails:
4/12

## Fetch 1/10th of the docs & give 1/100th of the docs with MMR search & lambda 0.3

In [14]:
from langchain.chains import RetrievalQA

print("Begin instantiating retriever.")
retriever = vectorstore.as_retriever(
    fetch_k=len(split_docs)//10,
    k=len(split_docs)//100,
    search_type='mmr',
    lambda_mult=0.3
)
print("Retriever instantiated.")
qa = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever
)
print("RAG chain instantiated.")

Begin instantiating retriever.
Retriever instantiated.
RAG chain instantiated.

## Test the RAG Model

In [15]:
questions = [
    "Where did Jesus talk about wine?",
    "Who was Abraham's son?",
    "Where did God send Jonah? And where did Jonah try to go instead?",
    "Who are Luke's books addressed to?",
    "Which psalm says that angels will protect you even from dashing your foot against a stone?",
    "Why did God regret making Saul the King of Israel?",
    "What did Paul disagree with Peter about according to Paul's letter to the Galatians? Who was right?",
    "Why did Peter feel comfortable eating pork and shellfish after receiving the Holy Spirit?",
    "When Jesus mentions that Moses lifted the serpent in the wilderness (John 3:14), what is He referencing?",
    "What is the genealogy of Enoch going back to Adam?",
    "Why did God flood the world in the time of Noah?",
    "What are the similarities between Daniel's prophesies and Revelation's prophesies?"
]
print("There are {} questions in the test suite.".format(len(questions)))

for question in questions:
    answer = qa.invoke(question)
    print(answer['query']+'\n'+answer['result']+'\n')

There are 12 questions in the test suite.
Where did Jesus talk about wine?
 The Bible mentions wine in numerous places, but it's important to note that these passages do not specifically refer to Jesus himself talking about wine. Here are a few examples where wine is mentioned in the New Testament:

1. At the wedding at Cana (John 2:1-11) - This is one of the first miracles performed by Jesus, in which he turns water into wine to save the hosts from embarrassment.

2. The Last Supper (Matthew 26:26-29, Mark 14:22-25, Luke 22:17-20, and 1 Corinthians 11:23-26) - Jesus shared a cup of wine with his disciples during the Last Supper, symbolizing his blood that would be shed for humanity.

3. The parable of the wicked husbandmen (Matthew 21:33-46, Mark 12:1-12, and Luke 20:9-19) - In this parable, Jesus uses wine as a symbol to explain his relationship with Israel.

4. The parable of the great supper (Luke 14:15-24) - In this parable, a man invites many guests to a wedding feast but they all make excuses not to attend. The master of the house then commands his servant to go out and invite the poor, crippled, blind, and lame so that his house will be filled. He also mentions wine in this parable as something provided for the guests at the feast.

5. Jesus' teaching on prayer (Matthew 6:9-13) - In the Lord's Prayer, Jesus says "Give us this day our daily bread," which can be interpreted to include wine, as it was a common staple of their diet.

Who was Abraham's son?
 Abraham did not have any sons mentioned in this particular passage. The offspring that came from Abraham's nephew Lot were Moab and Ammon, through incest with his daughters.

Where did God send Jonah? And where did Jonah try to go instead?
 In the provided Bible passage, there is no reference to Jonah. The story of Jonah occurs in another part of the Bible (Book of Jonah). God sent Jonah to the city of Nineveh, but Jonah tried to flee from going to Nineveh and went instead to Tarshish, which was believed to be on the western coast of Spain or Africa.

Who are Luke's books addressed to?
 The question you have asked refers to the New Testament book of Luke, not an Old Testament story like the one provided. The Gospel According to Luke was written by the physician and companion of Paul, Saint Luke. It is addressed to "Theophilus," a person whose identity remains unknown, as neither the New Testament nor any other ancient texts provide information about him. The book's intended audience is believed to be Christians in general rather than Theophilus specifically.

Which psalm says that angels will protect you even from dashing your foot against a stone?
 The Psalm that mentions angels protecting you even from stumbling over a stone is Psalm 91, specifically verse 12: "The LORD says, 'I will rescue those who love me. I will protect those who trust in my name.'" While the verse doesn't explicitly mention angels helping with this specific task, the broader context of the psalm often includes angels as protectors. The idea that angels will guide your steps and protect you from harm is a common theme in many religious texts and traditions.

Why did God regret making Saul the King of Israel?
 The passage provided does not mention any instance where God regretted making Saul the King of Israel. In the Hebrew Bible, God explicitly chooses Saul as the first king of Israel (1 Samuel 9:16), but later rejects him due to his disobedience and unfaithfulness (1 Samuel 15). After Saul is rejected, David becomes the new king of Israel. In the passage provided, it discusses the interactions between Abraham and God concerning the fate of Sodom and Gomorrah, but there is no mention of God regretting making Saul the King of Israel.

What did Paul disagree with Peter about according to Paul's letter to the Galatians? Who was right?
 In his letter to the Galatians, Paul disagreed with Peter (also known as Cephas) over the issue of circumcision and whether it was necessary for Gentile believers. According to Paul, the Gentiles were saved through faith in Christ without being obligated to follow Jewish laws, including circumcision (Galatians 2:1-3, 5:2-6). He argued that this was consistent with the message of grace and freedom in Christ that he had preached.

In Galatians 2:11-14, Paul describes an incident where Peter, who was initially supportive of this message for the Gentiles, began to withdraw from fellowship with them when some Jewish believers arrived. Paul confronted him about this hypocrisy and reminded him that he (Peter) had previously agreed with him on this matter.

Ultimately, both Paul and Peter were apostles of Jesus Christ, and their disagreement was not about who was right or wrong in a absolute sense but rather about the application of God's grace to the Gentile believers. The Bible doesn't provide a clear answer as to who was "right" in this specific instance, as both parties seemed to have legitimate concerns and were both acting in what they believed to be obedience to Christ. However, Paul's teachings about the inclusion of the Gentiles in the Church without requiring them to follow Jewish laws became foundational to Christianity and are affirmed throughout the New Testament.

Why did Peter feel comfortable eating pork and shellfish after receiving the Holy Spirit?
 The Bible does not provide specific guidance on why Peter felt comfortable eating pork and shellfish after receiving the Holy Spirit, as this is a matter of interpretation. In Acts 10:9-16, it is described that Peter had a vision in which he was instructed to eat unclean animals (which traditionally included pigs and many types of seafood). This vision was followed by a series of events in which God reiterated the message that there should be no distinction between Jews and Gentiles, including dietary laws. Some interpret this as an indication that dietary restrictions no longer apply after receiving the Holy Spirit. However, it's important to note that individual beliefs and practices can vary widely among different Christian denominations.

When Jesus mentions that Moses lifted the serpent in the wilderness (John 3:14), what is He referencing?
 In John 3:14, when Jesus refers to Moses lifting the serpent in the wilderness, He is speaking about an event recorded in the Old Testament book of Numbers. Specifically, it is Numbers 21:4-9 where we read that the Israelites, after being rescued from Egypt, complained about the lack of water and food. God sent poisonous snakes among them as a punishment, and many of the Israelites were bitten and died. The people then repented and asked Moses to pray for them. In response, God instructed Moses to fashion a bronze serpent on a pole and set it up on a pole, so that any Israelite who was bitten by a snake could look at the bronze serpent and live (Numbers 21:8-9). This event is often referred to as "The Bronze Serpent" or "The Serpent of Brass."

What is the genealogy of Enoch going back to Adam?
 The Bible does not provide a specific genealogy for Enoch that goes back to Adam. However, we know from Genesis 5:1-3 that Enoch was the son of Cainan and grandson of Jared. Here is the complete list of ancestors going back to Adam as given in Genesis:

* Adam
* Seth (Adam's third son)
* Enosh (Seth's son)
* Kenan (Enosh's son)
* Mahalalel (Kenan's son)
* Jared (Mahalalel's son)
* Enoch (Jared's son)
* Methuselah (Enoch's son)
* Lamech (Methuselah's father)
* Noe (Lamech's son, also known as Noah in other translations)

Why did God flood the world in the time of Noah?
 The biblical story explains that God flooded the world during the time of Noah to cleanse the earth from the wickedness and violence that had become widespread among humanity. According to the book of Genesis, humans had multiplied, their actions became corrupt, and their thoughts only evil continually. Therefore, God regretted that He had made mankind on the earth and was grieved at His heart. As a result, God decided to destroy all living things, except for Noah, his family, and the animals they took with them on the ark. After the flood, God made a covenant with Noah and established a new world order.

What are the similarities between Daniel's prophesies and Revelation's prophesies?
 The similarities between Daniel's prophecies and those in the Book of Revelation can be found in several aspects:

1. Symbolic Language: Both books use symbolic language, such as beasts, numbers, and visions, to depict future events that are difficult to understand without interpretation. For example, the four beasts in Daniel 7 and the seven seals in Revelation 6 both represent significant world empires and events.

2. Timeless Nature: Both books contain prophecies that were written in specific historical contexts but have timeless implications. Events described in these prophecies are yet to fully unfold, making it challenging to pinpoint their exact fulfillment.

3. Thematic Elements: Both Daniel and Revelation share common thematic elements such as the struggle between good and evil, God's sovereignty over human history, the ultimate triumph of righteousness, the role of Israel, and the coming of a Messianic figure (the Son of Man in Daniel, Jesus Christ in Revelation).

4. Eschatological Focus: Both books contain prophecies that are focused on end-time events, including the establishment of God's eternal kingdom, the resurrection of the dead, and the final judgment.

5. Interconnectedness: Some scholars believe that there is an interconnectedness between the prophecies in Daniel and Revelation, with certain images or themes appearing in both books and potentially pointing to a larger, unified vision of God's plan for humanity. For example, the four beasts in Daniel 7 are echoed by the seven heads and ten horns of the beast in Revelation 13, suggesting a continuity between world empires described in these prophetic passages.

6. Call to Repentance: Both books contain calls for individuals and nations to repent and turn away from sin, with the promise of ultimate salvation and eternal life for those who remain faithful to God.

## Assessment RAG -> 10th -> 100th w/ MMR @ 0.3 lambda
### Where did Jesus talk about wine?
The model fails to mention every instance where Jesus mentioned wine, and provides some where wine is not mentioned. The RAG model failed to help.
### Who was Abraham's son?
The model fails to mention Abraham's sons, and again was given the wrong RAG texts (about Lot).
### Where did God send Jonah? And where did Jonah try to go instead?
The model correctly identifies Nineveh and Tarshish, but the RAG texts are not about Jonah.
### Who are Luke's books addressed to?
The model correctly identifies Theophilus, but also says that the RAG texts provided were of the Old Testament.
### Which psalm says that angels will protect you even from dashing your foot against a stone?
The model correctly identifies Psalm 91, verse 12, but gets the quote wrong. **This is an odd hallucination.**
### Why did God regret making Saul the King of Israel?
The model correctly identifies the general reason for Saul's rejection. But again, the RAG text is about Sodom and Gomorah. **Why does the RAG model so often choose early Genesis chapters?!**
### What did Paul disagree with Peter about according to Paul's letter to the Galatians? Who was right?
The model correctly explains the issue, but is reluctant to say who was "right".
### Why did Peter feel comfortable eating pork and shellfish after receiving the Holy Spirit?
The model correctly explains the issue, but is reluctant to take a firm stance.
### When Jesus mentions that Moses lifted the serpent in the wilderness (John 3:14), what is He referencing?
The model correctly cites and explains the reference of the bronze serpent. It does not interpret the reference.
### What is the genealogy of Enoch going back to Adam?
The model give a genealogy going all the way to Noah, Enoch's grandson.
### Why did God flood the world in the time of Noah?
The model correctly identifies the purpose of the flood.
### What are the similarities between Daniel's prophesies and Revelation's prophesies?
The model correctly identifies some similarities between the 2 books.
### Score:
9/12
### RAG Fails:
5/12

## Fetch 50 of the docs & give 5 of the docs with MMR search & lambda 0.8.

In [16]:
from langchain.chains import RetrievalQA

print("Begin instantiating retriever.")
retriever = vectorstore.as_retriever(
    fetch_k=len(split_docs)//10,
    k=len(split_docs)//100,
    search_type='mmr',
    lambda_mult=0.8
)
print("Retriever instantiated.")
qa = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever
)
print("RAG chain instantiated.")

Begin instantiating retriever.
Retriever instantiated.
RAG chain instantiated.

## Test the RAG Model

In [17]:
questions = [
    "Where did Jesus talk about wine?",
    "Who was Abraham's son?",
    "Where did God send Jonah? And where did Jonah try to go instead?",
    "Who are Luke's books addressed to?",
    "Which psalm says that angels will protect you even from dashing your foot against a stone?",
    "Why did God regret making Saul the King of Israel?",
    "What did Paul disagree with Peter about according to Paul's letter to the Galatians? Who was right?",
    "Why did Peter feel comfortable eating pork and shellfish after receiving the Holy Spirit?",
    "When Jesus mentions that Moses lifted the serpent in the wilderness (John 3:14), what is He referencing?",
    "What is the genealogy of Enoch going back to Adam?",
    "Why did God flood the world in the time of Noah?",
    "What are the similarities between Daniel's prophesies and Revelation's prophesies?"
]
print("There are {} questions in the test suite.".format(len(questions)))

for question in questions:
    answer = qa.invoke(question)
    print(answer['query']+'\n'+answer['result']+'\n')

There are 12 questions in the test suite.
Where did Jesus talk about wine?
 The question asks about Jesus talking about wine, but the provided text does not include any mention of Jesus or the New Testament. In the New Testament, there are numerous instances where Jesus talks about, mentions, or uses wine in his teachings and parables. For example, in John 2:1-11, Jesus performs his first miracle by turning water into wine at a wedding in Cana of Galilee. In Matthew 26:26-29, Jesus institutes the Eucharist by saying, "This is my body, which is given for you. Do this in remembrance of me." In the same passage, he also says, "This cup that is poured out for you is the new covenant in my blood."

Who was Abraham's son?
 The question does not explicitly mention a specific son of Abraham, but it is important to note that Isaac was the only direct son mentioned in the passage provided and he was later considered as Abraham's primary son. However, this text focuses on the story of Lot, so there are no mentions of any sons born to Abraham during these events.

Where did God send Jonah? And where did Jonah try to go instead?
 In this text excerpt, there is no mention of Jonah. The narrative provided is from the Old Testament books of Genesis, specifically the story of Abraham and Sarah. Jonah, in a different part of the Bible, was called by God to go to Nineveh (present-day Mosul, Iraq) but instead tried to flee by boarding a ship bound for Tarshish (generally believed to be Tartessus, Spain or Tarshish in Israel). After being swallowed by a large fish and eventually repenting, he returned to Nineveh as God commanded.

Who are Luke's books addressed to?
 The question seems to have been mixed up as it refers to "Luke" but the passage provided is from the Old Testament and not the New Testament, where the Gospel according to Luke is found. In the New Testament, the Gospels are not specifically addressed to any particular person, they are written for all believers in general.

Which psalm says that angels will protect you even from dashing your foot against a stone?
 The answer can be found in Psalm 91, verse 12: "The LORD says, 'I will rescue those who love me. I will protect those who trust in my name.'" Although the psalm doesn't explicitly mention dashing one's foot against a stone, the implication is that God will keep His faithful safe from harm, including potential accidents like tripping or falling. In the story you provided, angels guided Lot and his family out of Sodom and Gomorrah, acting as divine protectors.

Why did God regret making Saul the King of Israel?
 The passage provided does not discuss God regretting making Saul the king of Israel. Instead, it tells a story about Abraham negotiating with God over the fate of Sodom and Gomorrah, not Saul. The first and second books of Samuel (1 Samuel in Christian Bible) detail how God eventually rejects Saul as king of Israel due to his disobedience.

What did Paul disagree with Peter about according to Paul's letter to the Galatians? Who was right?
 According to Paul's letter to the Galatians (Galatians 2:11-14), there was a disagreement between Paul and Peter (also called Cephas) about the matter of Jewish customs and the inclusion of Gentiles in the Christian community. The issue revolved around whether or not Gentile Christians needed to be circumcised and follow Jewish laws in order to be considered fully accepted by God and within the Christian faith.

Paul argued that there should be no distinction between Jews and Gentiles in the Christian church, as all are justified by faith in Christ alone (Galatians 3:28). In his view, requiring circumcision or adherence to Jewish customs would create a separation and undermine the message of grace that he preached.

Peter, on the other hand, seemed to be swayed by those who believed that circumcision was necessary for Gentile converts (Galatians 2:12). However, when confronted by Paul about this inconsistency, Peter withdrew and stopped eating with the Gentiles.

In this dispute, it is not explicitly stated in the passage from Galatians who was considered "right." Instead, the focus is on maintaining unity within the church and emphasizing faith in Christ as the means of salvation for all people, regardless of their background or adherence to Jewish customs. The passage suggests that both Paul and Peter were passionate about sharing the message of Christ but may have had differing perspectives on how best to do so in this specific situation.

Why did Peter feel comfortable eating pork and shellfish after receiving the Holy Spirit?
 The text provided is from the Old Testament of the Bible and does not directly address the question about Peter's diet after receiving the Holy Spirit, as this incident is described in the New Testament (Acts 10:9-23). In the New Testament, it is mentioned that Peter had a vision where God explicitly told him to eat unclean animals (such as pigs and other four-footed creatures and all kinds of beasts) and to no longer consider any animal impure. This vision signified that God was granting grace to the Gentiles, represented by these previously "unclean" animals. So, after receiving this vision, Peter felt comfortable eating food that he had previously considered unclean according to Jewish law.

When Jesus mentions that Moses lifted the serpent in the wilderness (John 3:14), what is He referencing?
 In the Old Testament book of Numbers, chapters 21 and 22, there is a story about the Israelites complaining to God while they were wandering in the desert after being freed from Egypt. As a result of their complaints, God sent venomous snakes among the people, biting many of them. The people repented, asked Moses to pray for them, and God instructed Moses to make a serpent out of bronze and put it on a pole. Anyone who had been bitten could look at the bronze serpent and be healed (Numbers 21:4-9). This event is often referred to as "Moses lifting the serpent in the wilderness." Jesus later referenced this event when speaking to Nicodemus in John 3:14, using it as a symbol of his own sacrifice that would bring salvation and healing to all who believed in him.

What is the genealogy of Enoch going back to Adam?
 The genealogy of Enoch in the Bible, going back to Adam, can be found in the Book of Genesis (5:1-32). Here it is summarized for you:

1. Adam
   - Son of God

2. Seth
   - Son of Adam

3. Enosh
   - Son of Seth

4. Kenan
   - Son of Enosh

5. Mahalalel
   - Son of Kenan

6. Jared
   - Son of Mahalalel

7. Enoch
   - Son of Jared

8. Methuselah
   - Son of Enoch

9. Lamech
   - Son of Methuselah

10. Noah
   - Son of Lamech

Why did God flood the world in the time of Noah?
 According to the biblical account, God flooded the world during the time of Noah due to the corruption and wickedness that had pervaded it. In Genesis 6:5-7 (KJV), it says, "The LORD saw that the wickedness of man was great in the earth, and that every imagination of the thoughts of his heart was only evil continually. And it repented the LORD that he had made man on the earth, and it grieved him at his heart. And the LORD said, I will destroy man whom I have created from the face of the earth; both man, and beast, and the creeping thing, and the fowls of the air; for it repenteth me that I have made them." God decided to send a great flood to cleanse the earth of sin and start anew with Noah and his family.

What are the similarities between Daniel's prophesies and Revelation's prophesies?
 The similarities between Daniel's prophecies and Revelation's prophecies mainly lie in their apocalyptic nature, use of symbolism, and their portrayal of a future conflict or judgment day. Here are some specific points of comparison:

1. Apocalyptic Imagery: Both books use vivid, symbolic imagery to describe supernatural events, including visions of beasts, four kingdoms, and judgments from God. For example, in Daniel 7, the prophet sees four beasts representing four empires that will rule on earth, while in Revelation 13, John sees a beast rising from the sea symbolizing an empire opposed to God.

2. Four Empires: Both books discuss four successive world powers or empires that will dominate history before the end times. In Daniel 2 and 7, the prophet sees four metallic empires representing Babylon, Medo-Persia, Greece, and Rome, while in Revelation 17:9-10 John sees seven mountains on which sits a woman symbolizing these same four empires plus three more (which are traditionally identified as the Holy Roman Empire, Ottoman Empire, and possibly the Revived Roman Empire).

3. End-Time Conflict and Judgment: Both books depict a future conflict between good and evil forces, often referred to as the "Battle of Armageddon" in Revelation 16:16. After this battle, God will judge the world and establish His kingdom on earth forever.

4. Symbolic Numbers: Both Daniel and Revelation use symbolic numbers to convey meaning. For example, in Daniel 9, a 70-week prophecy is given, which has been interpreted by many as referring to 70 weeks of years (490 years). Similarly, in Revelation, the number seven often represents completeness or perfection, and the number four is used to represent the four corners of the earth.

5. Eschatological Vision: Both books contain eschatological visions that offer insights into future events leading up to the end times. These visions provide guidance for believers in how to live in light of these upcoming events.

6. Interpretation and Debate: Due to their symbolic nature, both Daniel and Revelation have been subject to much interpretation and debate among scholars and theologians throughout history. Some interpretations focus on historical fulfilment, while others focus on future fulfillment or a combination of both.

## Assessment RAG -> 50 -> 5 w/ MMR @ 0.5 lambda
### Where did Jesus talk about wine?
The model mentions only 2 places where Jesus talked about wine. It also says the RAG model failed to provide New Testament texts.
### Who was Abraham's son?
The model mentions Isaac, but says that the RAG texts given were about Lot.
### Where did God send Jonah? And where did Jonah try to go instead?
The model mentions Nineveh and Tarshish, but says that the RAG texts given were about Abraham and Sarah.
### Who are Luke's books addressed to?
The model fails to mention Theophilus, and says the RAG model provided Old Testament texts.
### Which psalm says that angels will protect you even from dashing your foot against a stone?
The model correctly identifies Psalm 91, verse 12, but falsely quotes verse 14. **Is this a RAG hallucination?**
### Why did God regret making Saul the King of Israel?
The model mentions the portion of 1 Samuel that explains Saul's disobedience, but says that the RAG texts were from Genesis.
### What did Paul disagree with Peter about according to Paul's letter to the Galatians? Who was right?
The model correctly explains the issue of circumcision, but does not want to say who was "right".
### Why did Peter feel comfortable eating pork and shellfish after receiving the Holy Spirit?
The model correctly explains why Peter felt comfortable, but mentions the RAG texts are from the Old Testament.
### When Jesus mentions that Moses lifted the serpent in the wilderness (John 3:14), what is He referencing?
The model correctly identifies Numbers 21, and even mentions that Jesus was talking to Nicodemus in John 3:14.
### What is the genealogy of Enoch going back to Adam?
The model correctly lists the genealogy going all the way to Noah, Enoch's grandson.
### Why did God flood the world in the time of Noah?
The model clearly extracted the portion of Genesis about the flood. **The RAG selection is biased toward this area, but we know extraction works.**
### What are the similarities between Daniel's prophesies and Revelation's prophesies?
This is the best explanation of the similarities out of the 4 conditions.
### Score:
9/12
### RAG Fails:
6/12